name: Create Kafka Multi-Architecture Image

'on':
  workflow_dispatch:

jobs:
  manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create multi-architecture manifest
        run: |
          docker buildx imagetools create \
            --tag theencodedbong/kafka:3.9.2 \
            theencodedbong/kafka:3.9.2 \
            theencodedbong/kafka:3.9.2-amd64

      - name: Verify manifest
        run: |
          docker buildx imagetools inspect \
            theencodedbong/kafka:3.9.2